### ISSUE TITLE
Simpler dependency management

### ISSUE THREAD

**Issue by aminya** [JuliaMath/IntelVectorMath.jl#37]
Based on what is suggested in https://github.com/JuliaComputing/MKL.jl/issues/19#issuecomment-590046128 by @KristofferC:

> Use this way: https://github.com/JuliaSparse/Pardiso.jl/blob/81c8391e86cebaf71e936363664d878b22b1fd9a/src/Pardiso.jl#L37-L43.
> 
> There is nothing you need to do with this package here. Just depend on MLK_jll and do something like: https://github.com/JuliaSparse/Pardiso.jl/blob/81c8391e86cebaf71e936363664d878b22b1fd9a/src/Pardiso.jl#L25-L27 together with https://github.com/JuliaSparse/Pardiso.jl/blob/81c8391e86cebaf71e936363664d878b22b1fd9a/deps/build.jl#L67-L83.

We can use MKL_jill to provide the libraries.

**Comment by KristofferC** [comment]
I can see if I can get this working with MKL_jll later tonight.

**Comment by Crown421** [comment]
This is essentially already in #33 and firmly on my list of ToDos.
Two points here:
1. The reason why I have not started on using MKL_jll is that this would break the version for Julia <1.3 (as far as I understand). I was still thinking about maybe tackling a few of the other issues first, so that they are also available for older Julia versions. 
Unfortunately I had to catch up on research and this package is working as it is. 
2. I use this package mainly to learn things about Julia and SW development, and getting started on this something I am quite looking forward to. Therefore, if you think that moving to artifacts is important, I would not be sad to have a go at it first. I really appreciate the assistance, and might still need it, but I was quite looking forward to this one.

**Comment by aminya** [comment]
>     1. The reason why I have not started on using MKL_jll is that this would break the version for Julia <1.3 (as far as I understand). I was still thinking about maybe tackling a few of the other issues first, so that they are also available for older Julia versions.

There is no issue regarding that. Older Julia users can use the current version of IntelVectorMath!

**Comment by Crown421** [comment]
My point is that maybe #20 or #22 should be tackled first, so that they are in the version that older julia users can use.

**Comment by KristofferC** [comment]
>  I really appreciate the assistance, and might still need it, but I was quite looking forward to this one.

Sure, just ping me if you run into problems and maybe we can figure it out together.

**Comment by Crown421** [comment]
I just had a chance to take a look, and it seems that MKL.jll does not export `libmkl_vml_avx2`, which is the library that is being `ccall`ed here.
Will update once I know what do about it.

**Comment by aminya** [comment]
> 
> 
> My point is that maybe #20 or #22 should be tackled first, so that they are in the version that older julia users can use.

We can address #20 but, #22 doesn't have a solution for now.

**Comment by Crown421** [comment]
#39  now implements this.

**Comment by Crown421** [comment]
#39 is now merged and about to be registered
